config/routes.rb
  Rails.application.routes.draw do
  get 'go-solar-2015', to: 'static_pages#initiative', as: :initiative

  get 'home/index'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  root 'home#index'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Message from MMP Site",
      :to => "amankj@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      # render template: "home/index"
      redirect_to root_url, notice: "Thank you for your message. We will contact you soon!"

    else
      flash.now[:error] = 'Cannot send message.'
      render :nothing => true
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@contact = Contact.new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def initiative
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/create.html.haml
.container
  %h1 Thank you for your message.
  %p We'll get back to you soon.

app/views/contacts/new.html.haml
/ .div
/ 	- flash.each do |key, value|
/ 		%div
/ 			%a{"data-dismiss" => "alert", href: "#"} ×
/ 			= value
.contact_form
	= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f|
		= f.input :name, :required => true
		= f.input :email, :required => true
		= f.input :message, :as => :text, :required => true
		.hidden
			= f.input :nickname, :hint => 'Leave this field blank!'
		.submit-button
			= f.button :submit, 'Send message', :class=> "submit"

app/views/home/index.html.haml
/ = render partial: 'shared/banner'
= render partial: 'shared/toolbar'

.home
	.section#about
		= render partial: 'shared/about'

	.section#resources
		= render partial: 'shared/resources'

	.section#installations
		= render partial: 'shared/installations'
	


	.gradient
		.section#contact-us
			= render partial: 'shared/contactus'
	%a{ href: 'https://www.facebook.com/muellermegawatt', title: "Mueller Megawatt is on Facebook!", target: "blank" }

		.center
			%p Find us on
			= image_tag('facebook_logo.png')
	.thanks
		= render partial: 'shared/thanks'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Mueller Megawatt Project
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = favicon_link_tag

  %body
  / <p class="notice"><%= notice %></p>
  / <p class="alert"><%= alert %></p>

  .alerts
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
          %a.close{"data-dismiss" => "alert"}
            &times;
          = content_tag :div, msg, :id => "flash_#{name}"
  = yield

app/views/shared/_about.html.haml
.container#about-tab
	%ul.navigation#sub-nav
		%li
			%a{:href => "#about_us-tab", :id => "about"}About Us
		/ %li
		/ 	%a{:href => "#timeline-tab", :id => "timeline"}Timeline
		/ %li
		/ 	%a{:href => "#press-tab", :id => "press"}Press
		%li
			%a{:href => "#who-tab", :id => "who"}Who We are
		%li
			%a{:href => "#thanks-tab", :id => "thanks"}Thanks
		%li
			%a{:href => "#disclosure-tab", :id => "disclosure"}Disclosure

	#about_us-tab


		%h1 About Us
		.about-paragraph
			%p The Mueller Megawatt Project was started in the middle of 2009 to loosely organize a grassroots effort to go solar in the <a href="http://www.MuellerAustin.com/" target="_blank">Mueller Community</a> in Austin, TX. The ultimate goal of the group was to see one Megawatt (1,000 kilowatts) of solar capacity installed in the Mueller neighborhood. After the group's namesake was achieved in the summer of 2011, solar capacity has continued to grow in the neighborhood.
			%br
			%p If you are interested in going solar in Mueller - please check out the 10 Step to Go Solar in Mueller guide along with the rest of the resources on the site. If you don't live in Mueller, please feel free to use our resources to help determine if going solar is right for you.
		.goal
			%p Goal
			.box#capacity
				.stat
					%p 1.00 MW
				.label
					%p Installed Capacity
			.box#install-count
				.stat
					%p 200 
				.label
					%p Installations
			.box#goalpercent
				.stat
					%p 100%
				.label
					%p Percent of Goal
		.achieved
			%p Current
			.box#capacity
				.stat
					%p 1.51 MW
				.label
					%p Installed Capacity
			.box#install-count
				.stat
					%p 277 
				.label
					%p Installations
			.box#goalpercent
				.stat
					%p 151%
				.label
					%p Percent of Goal	

	#timeline-tab 	
		%h1 Timeline
		.timeline
			%p This is timeline content.
	#press-tab 
		%h1 Press
		.press
			%p This is press content.
	#who-tab
		= render partial: 'shared/who'
	#thanks-tab 
		%h1	Thanks
		%p We would like to give special thanks to Austin Energy and Pecan Street, Inc., whose generous financial incentives made our goals possible.
		%ul
			%li 
			= link_to image_tag('austin-energy-logo.png'), 'http://www.austinenergy.com'
			%li 
			= link_to image_tag('pecan-street-logo.jpg'), 'http://www.pecanstreet.org'

	#disclosure-tab 
		%h1	Disclosure
		%p Members of the Mueller Megawatt Project do not have a financial interest in any solar installers and do not make money off solar consultations they provide to Mueller homeowners. They do, however, accept free beer with a smile.
#courtesy
	%p Photo Courtesy of: <a href="http://www.pecanstreet.org/" target="_blank">Pecan Street Inc.</a> 

app/views/shared/_banner.html.haml
.banner
	.message
		%p#hey
			=link_to "GO SOLAR NOW", initiative_path
		%P 
			=link_to "Learn about the GO SOLAR 2015 Initiative", initiative_path

	%p#learn-more or Scroll Down to learn more about the Mueller Megawatt Project

	.down-arrow
		= image_tag('icons/previous.png')

app/views/shared/_contactus.html.haml
- @contact = Contact.new

.container#contact-us-tab.anchor
	%h1 Contact Us

	= render template: "contacts/new"

	.cloud1
		= image_tag('cloud-1.png') 
	.cloud2
		= image_tag('cloud-2.png') 
	.cloud3
		= image_tag('cloud-3.png') 		
	.cloud4
		= image_tag('cloud-4.png') 
	.cloud5
		= image_tag('cloud-5.png') 

app/views/shared/_heatmap.html.haml
%h1 Map

<iframe width="100%" height="600" scrolling="no" frameborder="no" src="https://www.google.com/fusiontables/embedviz?q=select+col2+from+1MXFzMJdnIMfeNdQTz36pARPgpE_uhqJvL2kUhDU&amp;viz=MAP&amp;h=false&amp;lat=30.292246758681166&amp;lng=-97.70263978115084&amp;t=1&amp;z=17&amp;l=col2"></iframe>


.addyourinstall
	%p Don't see your Install? Send your name, address, system installer and system size to add@muellermegawatt.org

app/views/shared/_installations.html.haml
.container#installations-tab.anchor
	%ul.navigation#sub-nav
		%li
			%a{:href => "#map-tab", :id => "map"}Map
		/ %li
		/ 	%a{:href => "#heatmap-tab", :id => "map"}Heat Map
		%li
			%a{:href => "#pictures-tab", :id => "pictures"}Pictures

	.content#map-tab.list
		= render partial: 'shared/map'
	.content#heatmap-tab.list
		= render partial: 'shared/heatmap'
	.content#pictures-tab.list
		= render partial: 'shared/pictures'

app/views/shared/_map.html.haml
%h1 Map

/ <iframe width="1200" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps/ms?ie=UTF8&amp;oe=UTF8&amp;msa=0&amp;msid=203218300729472956960.00049b3a1d65ec1946306&amp;t=m&amp;ll=30.292664,-97.703798&amp;spn=0.011117,0.025728&amp;z=16&amp;output=embed"></iframe><br />

<iframe width="100%" height="600" scrolling="no" frameborder="no" src="https://www.google.com/fusiontables/embedviz?q=select+col2+from+1MXFzMJdnIMfeNdQTz36pARPgpE_uhqJvL2kUhDU&amp;viz=MAP&amp;h=false&amp;lat=30.292246758681166&amp;lng=-97.70263978115084&amp;t=1&amp;z=17&amp;l=col2"></iframe>

.addyourinstall
	%p Don't see your Install? Send your name, address, system installer and system size to add@muellermegawatt.org

app/views/shared/_overview.html.haml
%h1 Overview

app/views/shared/_pictures.html.haml
%h1 Pictures

%ul#lightSlider
	%li{"data-thumb" => "/assets/solar-pic-1.jpg"}
		= image_tag('solar-pic-1.jpg')
	%li{"data-thumb" => "/assets/solar-pic-2.jpg"}
		= image_tag('solar-pic-2.jpg')
	%li{"data-thumb" => "/assets/solar-pic-3.jpg"}
		= image_tag('solar-pic-3.jpg')
	%li{"data-thumb" => "/assets/solar-pic-4.jpg"}
		= image_tag('solar-pic-4.jpg')
	%li{"data-thumb" => "/assets/solar-pic-5.jpg"}
		= image_tag('solar-pic-5.jpg')
	%li{"data-thumb" => "/assets/solar-pic-6.jpg"}
		= image_tag('solar-pic-6.jpg')
	%li{"data-thumb" => "/assets/solar-pic-7.jpg"}
		= image_tag('solar-pic-7.jpg')
	%li{"data-thumb" => "/assets/solar-pic-8.jpg"}
		= image_tag('solar-pic-8.jpg')
	%li{"data-thumb" => "/assets/solar-pic-9.jpg"}
		= image_tag('solar-pic-9.jpg')
	%li{"data-thumb" => "/assets/solar-pic-10.jpg"}
		= image_tag('solar-pic-10.jpg')
	%li{"data-thumb" => "/assets/solar-pic-11.jpg"}
		= image_tag('solar-pic-11.jpg')
	%li{"data-thumb" => "/assets/solar-pic-12.jpg"}
		= image_tag('solar-pic-12.jpg')
	%li{"data-thumb" => "/assets/solar-pic-13.jpg"}
		= image_tag('solar-pic-13.jpg')
	%li{"data-thumb" => "/assets/solar-pic-14.jpg"}
		= image_tag('solar-pic-14.jpg')
	%li{"data-thumb" => "/assets/solar-pic-15.jpg"}
		= image_tag('solar-pic-15.jpg')
	%li{"data-thumb" => "/assets/solar-pic-16.jpg"}
		= image_tag('solar-pic-16.jpg')
	%li{"data-thumb" => "/assets/solar-pic-17.jpg"}
		= image_tag('solar-pic-17.jpg')
	%li{"data-thumb" => "/assets/solar-pic-18.jpg"}
		= image_tag('solar-pic-18.jpg')
	%li{"data-thumb" => "/assets/solar-pic-19.jpg"}
		= image_tag('solar-pic-19.jpg')
	%li{"data-thumb" => "/assets/solar-pic-20.jpg"}
		= image_tag('solar-pic-20.jpg')
	%li{"data-thumb" => "/assets/solar-pic-21.jpg"}
		= image_tag('solar-pic-21.jpg')
	%li{"data-thumb" => "/assets/solar-pic-22.jpg"}
		= image_tag('solar-pic-22.jpg')
	%li{"data-thumb" => "/assets/solar-pic-23.jpg"}
		= image_tag('solar-pic-23.jpg')
	%li{"data-thumb" => "/assets/solar-pic-24.jpg"}
		= image_tag('solar-pic-24.jpg')
	%li{"data-thumb" => "/assets/solar-pic-25.jpg"}
		= image_tag('solar-pic-25.jpg')
	%li{"data-thumb" => "/assets/solar-pic-26.jpg"}
		= image_tag('solar-pic-26.jpg')
	%li{"data-thumb" => "/assets/solar-pic-27.jpg"}
		= image_tag('solar-pic-27.jpg')
	%li{"data-thumb" => "/assets/solar-pic-28.jpg"}
		= image_tag('solar-pic-28.jpg')
	%li{"data-thumb" => "/assets/solar-pic-29.jpg"}
		= image_tag('solar-pic-29.jpg')
	%li{"data-thumb" => "/assets/solar-pic-30.jpg"}
		= image_tag('solar-pic-30.jpg')
	%li{"data-thumb" => "/assets/solar-pic-31.jpg"}
		= image_tag('solar-pic-31.jpg')
	%li{"data-thumb" => "/assets/solar-pic-32.jpg"}
		= image_tag('solar-pic-32.jpg')
	%li{"data-thumb" => "/assets/solar-pic-33.jpg"}
		= image_tag('solar-pic-33.jpg')
	%li{"data-thumb" => "/assets/solar-pic-34.jpg"}
		= image_tag('solar-pic-34.jpg')
	%li{"data-thumb" => "/assets/solar-pic-35.jpg"}
		= image_tag('solar-pic-35.jpg')
	%li{"data-thumb" => "/assets/solar-pic-36.jpg"}	
		= image_tag('solar-pic-36.jpg')
	%li{"data-thumb" => "/assets/solar-pic-37.jpg"}
		= image_tag('solar-pic-37.jpg')
	%li{"data-thumb" => "/assets/solar-pic-38.jpg"}
		= image_tag('solar-pic-38.jpg')
	%li{"data-thumb" => "/assets/solar-pic-39.jpg"}
		= image_tag('solar-pic-39.jpg')
	%li{"data-thumb" => "/assets/solar-pic-40.jpg"}
		= image_tag('solar-pic-40.jpg')
	%li{"data-thumb" => "/assets/solar-pic-41.jpg"}
		= image_tag('solar-pic-41.jpg')
	%li{"data-thumb" => "/assets/solar-pic-42.jpg"}
		= image_tag('solar-pic-42.jpg')
	%li{"data-thumb" => "/assets/solar-pic-43.jpg"}
		= image_tag('solar-pic-43.jpg')
	%li{"data-thumb" => "/assets/solar-pic-44.jpg"}
		= image_tag('solar-pic-44.jpg')
	%li{"data-thumb" => "/assets/solar-pic-45.jpg"}
		= image_tag('solar-pic-45.jpg')
	%li{"data-thumb" => "/assets/solar-pic-46.jpg"}	
		= image_tag('solar-pic-46.jpg')
	%li{"data-thumb" => "/assets/solar-pic-47.jpg"}
		= image_tag('solar-pic-47.jpg')
	%li{"data-thumb" => "/assets/solar-pic-48.jpg"}
		= image_tag('solar-pic-48.jpg')
	%li{"data-thumb" => "/assets/solar-pic-49.jpg"}
		= image_tag('solar-pic-49.jpg')
	%li{"data-thumb" => "/assets/solar-pic-50.jpg"}
		= image_tag('solar-pic-50.jpg')
	%li{"data-thumb" => "/assets/solar-pic-51.jpg"}
		= image_tag('solar-pic-51.jpg')
	%li{"data-thumb" => "/assets/solar-pic-52.jpg"}
		= image_tag('solar-pic-52.jpg')
	%li{"data-thumb" => "/assets/solar-pic-53.jpg"}
		= image_tag('solar-pic-53.jpg')

app/views/shared/_resources.html.haml
.container#resources-tab.anchor

	%ul.navigation#sub-nav
		%li
			%a{:href => "#solar-faq-tab", :id => "solar-faq"}Solar FAQ
		/ %li
		/ 	%a{:href => "#solar-dictionary-tab", :id => "solar-dictionary"}Solar Dictionary
		/ %li
		/ 	%a{:href => "#tens-steps-tab", :id => "ten-steps"}Mueller 10 Steps to Go Solar
		%li
			%a{:href => "#useful-links-tab", :id => "useful-links"}Useful Links	
	.content#solar-faq-tab.list
		= render partial: 'shared/solarfaq'
	.content#solar-dictionary-tab.list
		= render partial: 'shared/solardictionary'
	.content#solar-dictionary-tab.list
		= render partial: 'shared/tensteps'
	.content#useful-links-tab 
		%h1 Useful Links 

app/views/shared/_solardictionary.html.haml
%h1 Solar Dictionary
.download
	.pdf-icon
		= image_tag('pdf-icon-32px.png') 
		<a href="http://www.MuellerAustin.com/" target="_blank">Download the Solar Dictionary</a>
%ul#solar-dictionary
	%li
		%a{:href => "#alternating-current-tab", :id => "alternating-current"}Alternating Current
	%li
		%a{:href => "#solar-array-tab", :id => "solar-array"}Array
	%li
		%a{:href => "#azimuth-tab", :id => "azimuth"}Azimuth
	%li
		%a{:href => "#alternating-current-tab", :id => "alternating-current"}Alternating Current
	%li
		%a{:href => "#solar-array-tab", :id => "solar-array"}Array
	%li
		%a{:href => "#azimuth-tab", :id => "azimuth"}Azimuth
	%li
		%a{:href => "#alternating-current-tab", :id => "alternating-current"}Alternating Current
	%li
		%a{:href => "#solar-array-tab", :id => "solar-array"}Array
	%li
		%a{:href => "#azimuth-tab", :id => "azimuth"}Azimuth
	%li
		%a{:href => "#alternating-current-tab", :id => "alternating-current"}Alternating Current
	%li
		%a{:href => "#solar-array-tab", :id => "solar-array"}Array
	%li
		%a{:href => "#azimuth-tab", :id => "azimuth"}Azimuth
	%li
		%a{:href => "#alternating-current-tab", :id => "alternating-current"}Alternating Current
	%li
		%a{:href => "#solar-array-tab", :id => "solar-array"}Array
	%li
		%a{:href => "#azimuth-tab", :id => "azimuth"}Azimuth
	%li
		%a{:href => "#alternating-current-tab", :id => "alternating-current"}Alternating Current
	%li
		%a{:href => "#solar-array-tab", :id => "solar-array"}Array
	%li
		%a{:href => "#azimuth-tab", :id => "azimuth"}Azimuth
	%li
		%a{:href => "#alternating-current-tab", :id => "alternating-current"}Alternating Current
	%li
		%a{:href => "#solar-array-tab", :id => "solar-array"}Array
	%li
		%a{:href => "#azimuth-tab", :id => "azimuth"}Azimuth
	%li
		%a{:href => "#alternating-current-tab", :id => "alternating-current"}Alternating Current
	%li
		%a{:href => "#solar-array-tab", :id => "solar-array"}Array
	%li
		%a{:href => "#azimuth-tab", :id => "azimuth"}Azimuth

.dictionary#alternating-current-tab
	%h2 Alternating Current
	%p AC is the form of electric power delivered to businesses and residences. Solar arrays produce direct current (DC) electric power. In order to convert from DC power to AC power, an inverter is needed. In combination with other losses in the system (wiring, heat, etc.), about 23% of the power is lost, often referred to as the "Derate Factor". 
.dictionary#solar-array-tab
	%h2 Array
.dictionary#azimuth-tab
	%h2 Azimuth 

app/views/shared/_thanks.html.haml
%ul#thanks-footer 
	%li Built using free/open source software:
	%li 
		=link_to "Ruby on Rails", "http://rubyonrails.org/", target: "blank"
	%li
		=link_to "Heroku", "http://heroku.com/", target: "blank"
	%li
		=link_to "LightSlider", "http://sachinchoolur.github.io/lightslider/index.html", target: "blank"
	%li
		=link_to "Google Maps", "http://maps.google.com/", target: "blank"
	%li 
		=link_to "Foreman", "https://github.com/ddollar/foreman", target: "blank"
	%li 
		=link_to "Simple Form", "https://github.com/plataformatec/simple_form", target: "blank"
	%li 
		=link_to "JQuery", "http://jquery.com/", target: "blank"
	%li 		
		=link_to "Mail Form", "https://github.com/plataformatec/mail_form", target: "blank"
	%li 
	%p © 2015 • Mueller Megawatt Project

app/views/shared/_toolbar.html.haml
.toolbar-anchor
.toolbar
	.container
		.logo
			= image_tag('MMP-logo-small.png') 

		/ .excuse
		/ 	%p Currently Mobilizing: Learn More about the 2015 MMP Group Purchase Program

		%ul.navigation#nav-main
			/ %li
			/ 	=link_to "Solar 2015", "http://www.muellermegawatt.org/go-solar-2015", :class => "emphasis"
			%li 
				%a.active{:href => "#about"} About
				/ %ul#dropdown
				/ 	%li
				/ 		%a{:href => "#"} About Us
				/ 	%li
				/ 		%a{:href => "#"} Timeline
				/ 	%li
				/ 		%a{:href => "#"} Press
				/ 	%li
				/ 		%a{:href => "#"} Thanks
				/ 	%li
				/ 		%a{:href => "#"} Disclosure		


			%li 
				%a{:href => "#resources-tab"} Resources
				/ %ul#dropdown
				/ 	%li
				/ 		%a{:href => "#"} Solar FAQ
				/ 	%li
				/ 		%a{:href => "#"} Solar Dictionary
				/ 	%li
				/ 		%a{:href => "#"} Useful Links


			%li 
				%a{:href => "#installations-tab"} Installations
				/ %ul#dropdown
				/ 	%li
				/ 		%a{:href => "#"} Statistics
				/ 	%li
				/ 		%a{:href => "#"} Map
				/ 	%li
				/ 		%a{:href => "#"} Pictures
			%li 
				%a{:href => "#contact-us-tab"} Contact Us

app/views/shared/_who.html.haml
%h1 Who We Are

#who_we_are
	%ul 
		%li
			.headshot
				= image_tag('aman.jpg') 
			.bio
				%h3 Aman Jain
				%p Aman has an unhealthy obsession with Microsoft Excel. Thankfully, he was able to channel his disease into a spreadsheet to help him and his neighbors figure out if it made financial sense to go solar. Turns out, it did.
		%li
			.headshot
				= image_tag('dan.jpg') 
			.bio
				%h3 Dan McAtee
				%p We've spent so much time at Dan's house for meetings that we should probably pay him rent. He doesn't take no for an answer and honestly, can be a little intimidating.
	%ul 
		%li
			.headshot
				= image_tag('dusty.jpg') 
			.bio
				%h3 Dusty Harshman
				%p Dusty's brain imagined the "Mueller Megawatt Project" and his hands typed out the idea in a neighborhood forum several years ago. The rest is history.
		%li
			.headshot
				= image_tag('kathy.jpg') 
			.bio
				%h3 Kathy Sokolic
				%p Kathy does everything. Literally.
	%ul 
		%li
			.headshot
				= image_tag('art.jpg') 
			.bio
				%h3 Art Dadonna
				%p Art's speciality is engineering. His expertise has helped the entire neighborhood get comfortable with the technology we're putting on our roofs.
		%li
			.headshot
				= image_tag('dhananjay.jpg') 
			.bio
				%h3 Dhananjay Joshi
				%p Dhananjay always has a positive attitude and is usually the first volunteer. We couldn't have reached our goals without people like him.
%p ...plus many more!!!